### ISSUE TITLE
Bug: mangarock.com

### ISSUE THREAD

**Issue by alexanderdegre** [yuru-yuri/manga-dl#183] opened 2019-05-18 13:47 UTC
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Arch Linux (5.1.2-arch1-1-ARCH)
Python version | 3.7.3
Pip version | 19.0.3
Manga-py version | 1.5.5.2
URL | https://mangarock.com/manga/mrs-serie-100226981
. | https://mangarock.com/manga/mrs-serie-100114548
. | ...

#### To Reproduce:
1. Run `manga-py https://mangarock.com/manga/mrs-serie-100226981`
1. Command fails

#### Additional context
All downloads for mangarock seem to be broken at the moment. Possibly they changed how manga is delivered

Trying to download any manga from mangarock results in an error like this before anything can download at all:

```
[me@pc downloads]$ manga-py https://mangarock.com/manga/mrs-serie-100114548

2019-05-18 15:33:01.162 | ERROR    | manga_py.cli:start:45 - An error has been caught in function 'start', process 'MainProcess' (7963), thread 'MainThread' (140140626380416):
Traceback (most recent call last):

  File "/home/me/.local/bin/manga-py", line 11, in <module>
    load_entry_point('manga-py==1.5.5.2', 'console_scripts', 'manga-py')()
    └ <function load_entry_point at 0x7f75071f8268>

  File "/home/me/.local/lib/python3.7/site-packages/manga_py/__init__.py", line 93, in main
    code, _info = _run_util(args)
                  │         └ ArgumentParser(prog='manga-py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler...
                  └ <function _run_util at 0x7f75070c4730>
  File "/home/me/.local/lib/python3.7/site-packages/manga_py/__init__.py", line 52, in _run_util
    code = _init_cli(args, _info)
           │         │     └ <manga_py.info.Info object at 0x7f7507f54160>
           │         └ ArgumentParser(prog='manga-py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler...
           └ <function _init_cli at 0x7f75070c46a8>
  File "/home/me/.local/lib/python3.7/site-packages/manga_py/__init__.py", line 40, in _init_cli
    cli_mode.start()
    │        └ <bound method Cli.start of <manga_py.cli.Cli object at 0x7f75071a7b38>>
    └ <manga_py.cli.Cli object at 0x7f75071a7b38>
> File "/home/me/.local/lib/python3.7/site-packages/manga_py/cli/__init__.py", line 45, in start
    self.parser.start()
    │    │      └ <bound method Parser.start of <manga_py.parser.Parser object at 0x7f75071a79b0>>
    │    └ <manga_py.parser.Parser object at 0x7f75071a79b0>
    └ <manga_py.cli.Cli object at 0x7f75071a7b38>
  File "/home/me/.local/lib/python3.7/site-packages/manga_py/parser.py", line 44, in start
    self.provider.process(self.params['url'], self.params)
    │    │        │       │    │              │    └ {'url': 'https://mangarock.com/manga/mrs-serie-100114548', 'name': '', 'destination': 'Manga', 'no_progress': False, 'not_change...
    │    │        │       │    │              └ <manga_py.parser.Parser object at 0x7f75071a79b0>
    │    │        │       │    └ {'url': 'https://mangarock.com/manga/mrs-serie-100114548', 'name': '', 'destination': 'Manga', 'no_progress': False, 'not_change...
    │    │        │       └ <manga_py.parser.Parser object at 0x7f75071a79b0>
    │    │        └ <bound method Provider.process of <manga_py.providers.mangarock_com.MangaRockCom object at 0x7f75071a7438>>
    │    └ <manga_py.providers.mangarock_com.MangaRockCom object at 0x7f75071a7438>
    └ <manga_py.parser.Parser object at 0x7f75071a79b0>
  File "/home/me/.local/lib/python3.7/site-packages/manga_py/provider.py", line 83, in process
    self.loop_chapters()
    │    └ <bound method Provider.loop_chapters of <manga_py.providers.mangarock_com.MangaRockCom object at 0x7f75071a7438>>
    └ <manga_py.providers.mangarock_com.MangaRockCom object at 0x7f75071a7438>
  File "/home/me/.local/lib/python3.7/site-packages/manga_py/provider.py", line 114, in loop_chapters
    self._info.add_volume(self.chapter_for_json(), self.get_archive_path())
    │    │     │          │    │                   │    └ <bound method Provider.get_archive_path of <manga_py.providers.mangarock_com.MangaRockCom object at 0x7f75071a7438>>
    │    │     │          │    │                   └ <manga_py.providers.mangarock_com.MangaRockCom object at 0x7f75071a7438>
    │    │     │          │    └ <bound method MangaRockCom.chapter_for_json of <manga_py.providers.mangarock_com.MangaRockCom object at 0x7f75071a7438>>
    │    │     │          └ <manga_py.providers.mangarock_com.MangaRockCom object at 0x7f75071a7438>
    │    │     └ <bound method Info.add_volume of <manga_py.info.Info object at 0x7f7507f54160>>
    │    └ <manga_py.info.Info object at 0x7f7507f54160>
    └ <manga_py.providers.mangarock_com.MangaRockCom object at 0x7f75071a7438>
  File "/home/me/.local/lib/python3.7/site-packages/manga_py/provider.py", line 181, in get_archive_path
    _path + '.%s%s' % (additional_data_name, self._archive_type())
    │                  │                     │    └ <bound method Base._archive_type of <manga_py.providers.mangarock_com.MangaRockCom object at 0x7f75071a7438>>
    │                  │                     └ <manga_py.providers.mangarock_com.MangaRockCom object at 0x7f75071a7438>
    │                  └ ''
    └ 'vol_000'
  File "/home/me/.local/lib/python3.7/site-packages/manga_py/fs.py", line 73, in path_join
    return str(Path(_path).joinpath(*args))
           │   │    │                └ (None, 'vol_000.zip')
           │   │    └ 'Manga'
           │   └ <class 'pathlib.Path'>
           └ <class 'str'>
  File "/usr/lib/python3.7/pathlib.py", line 898, in joinpath
    return self._make_child(args)
           │    │           └ (None, 'vol_000.zip')
           │    └ <bound method PurePath._make_child of PosixPath('Manga')>
           └ PosixPath('Manga')
  File "/usr/lib/python3.7/pathlib.py", line 688, in _make_child
    drv, root, parts = self._parse_args(args)
                       │    │           └ (None, 'vol_000.zip')
                       │    └ <bound method PurePath._parse_args of <class 'pathlib.PosixPath'>>
                       └ PosixPath('Manga')
  File "/usr/lib/python3.7/pathlib.py", line 642, in _parse_args
    a = os.fspath(a)
    │   │  │      └ None
    │   │  └ <built-in function fspath>
    │   └ <module 'os' from '/usr/lib/python3.7/os.py'>
    └ None

TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by 1271** [comment] 2019-05-20 06:58
Thanks for the issue. I will check it

**Comment by gromenauer** [comment] 2019-05-21 08:42
Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.5.5.2
URL | `https://mangarock.com/manga/mrs-serie-100226981` Dont' work :bug: :boom: 
URL | `https://mangarock.com/manga/mrs-serie-100114548` Dont' work :bug: :boom: 
URL | `https://mangarock.com/manga/mrs-serie-100058029` Dont' work :bug: :boom: 
URL | `https://mangarock.com/manga/mrs-serie-100096263` Strange case. Works when downloading just the last chapters (it download a duplicate of 14 and 15 as 16 and 17), but breaks when downloading all :bug: :boom: .

**Comment by 1271** [comment] 2019-05-22 05:32
So. I finally get my hands today to this issue.
The site has changed ... yes :-)
Now you can not just get the content. However, it is even better for us. They have an API. It's good
The logic will be slightly simplified. Wait for updates in the next day

**Comment by gromenauer** [comment] 2019-06-02 15:06
Working for me now :+1: 
@alexanderdegre, Is it working for you in this version?

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.5.6.1
URL | `https://mangarock.com/manga/mrs-serie-100226981`
URL | `https://mangarock.com/manga/mrs-serie-100114548`
URL | `https://mangarock.com/manga/mrs-serie-100058029`
URL | `https://mangarock.com/manga/mrs-serie-100096263`

**Comment by 1271** [comment] 2019-06-19 17:57
I close this issue. If you still have a problem, click "Reopen issue"

**Closed by 1271** 2019-06-19 17:57 UTC
Labels: bug
